### ISSUE TITLE
It seems that the dependencies are broken in 0.7.0

### ISSUE THREAD

**Issue by snowwolf007cn** [jsonld-java/jsonld-java#157]
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/http/config/Lookup
	at com.github.jsonldjava.core.DocumentLoader.getDefaultHttpClient(DocumentLoader.java:132)
	at com.github.jsonldjava.core.DocumentLoader.getHttpClient(DocumentLoader.java:150)
	at com.github.jsonldjava.core.DocumentLoader.openStreamFromURL(DocumentLoader.java:109)
	at com.github.jsonldjava.core.DocumentLoader.fromURL(DocumentLoader.java:62)
	at com.github.jsonldjava.core.DocumentLoader.loadDocument(DocumentLoader.java:31)
	at com.github.jsonldjava.core.Context.parse(Context.java:169)
	at com.github.jsonldjava.core.Context.parse(Context.java:252)
	at com.github.jsonldjava.core.JsonLdApi.expand(JsonLdApi.java:534)
	at com.github.jsonldjava.core.JsonLdApi.expand(JsonLdApi.java:981)
	at com.github.jsonldjava.core.JsonLdProcessor.expand(JsonLdProcessor.java:146)
	at com.github.jsonldjava.core.JsonLdProcessor.expand(JsonLdProcessor.java:177)
	at com.wanda.hds.schema.Parser.main(Parser.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
Caused by: java.lang.ClassNotFoundException: org.apache.http.config.Lookup
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	... 17 more

**Comment by snowwolf007cn** [comment]
I looked up into the source code, seems that the package doesn't include the right <version> for httpcore-osgi, you may fix this.

**Comment by ansell** [comment]
The httpcore-osgi library is included as a Maven dependency. Are you using Maven to manage your dependencies?

Could you post a short maven file and a test Java file that demonstrate the error?

**Comment by snowwolf007cn** [comment]
Yes, Below is part of the POM:
```
        <dependency>
            <groupId>com.github.jsonld-java</groupId>
            <artifactId>jsonld-java</artifactId>
            <version>0.7.0</version>
        </dependency>
```

but seems that this will download http components 4.2.5, so I have to manually add these two and solve the problem:
```
        <dependency>
            <groupId>org.apache.httpcomponents</groupId>
            <artifactId>httpclient-osgi</artifactId>
            <version>4.5.1</version>
        </dependency>

        <dependency>
            <groupId>org.apache.httpcomponents</groupId>
            <artifactId>httpcore-osgi</artifactId>
            <version>4.4.4</version>
        </dependency>
```

Here is a code sample from my project:
```
            URL url = new URL("http://localhost/hds-mapping/member/hds-mapping-card.jsonld");
            InputStream in = url.openStream();
            
            Object jsonObject = JsonUtils.fromInputStream(in);
            Object result = JsonLdProcessor.expand(jsonObject);


            System.out.println(JsonUtils.toPrettyString(result));
```

**Comment by ansell** [comment]
One issue that may be related is the illogical (likely incorrect) use of "scope=provided" to link back to httpcore from httpclient, which tells maven not to actually pull in the dependencies. Hence, I will need to specify all of the dependencies manually, just incase the Apache HTTPClient team have done this for any of the other cases also.

See the following chunk demonstrating their bug from https://search.maven.org/remotecontent?filepath=org/apache/httpcomponents/httpclient-osgi/4.5.1/httpclient-osgi-4.5.1.pom :

    <dependency>
        <groupId>org.apache.httpcomponents</groupId>
        <artifactId>httpcore</artifactId>
        <scope>provided</scope>
    </dependency>

**Comment by ansell** [comment]
Closing this issue after bumping all versions away from 4.2.5 series given that other libraries seem to be mostly using the 4.5.1/4.4.4 combination now.
