### ISSUE TITLE
Presence of ampersand in jsonld causes java.net.URISyntaxException

### ISSUE THREAD

**Issue by lewismc** [jsonld-java/jsonld-java#217]
Using both jsonld-java 0.10.0 and 0.11.1 with the any23.org Webservice, I get the following error when attempting to extract structured content from https://www.rottentomatoes.com/m/the_lord_of_the_rings_the_fellowship_of_the_ring/ 
```
<?xml version="1.0" encoding="UTF-8" ?>
<report>
<message>Internal error.</message>
<error>
<![CDATA[
java.lang.IllegalArgumentException: Illegal character in path at index 6: Action &amp; Adventure
	at java.net.URI.create(URI.java:852)
	at java.net.URI.resolve(URI.java:1036)
	at com.github.jsonldjava.utils.JsonLdUrl.resolve(JsonLdUrl.java:274)
	at com.github.jsonldjava.core.Context.expandIri(Context.java:538)
	at com.github.jsonldjava.core.Context.expandValue(Context.java:1099)
	at com.github.jsonldjava.core.JsonLdApi.expand(JsonLdApi.java:979)
	at com.github.jsonldjava.core.JsonLdApi.expand(JsonLdApi.java:517)
	at com.github.jsonldjava.core.JsonLdApi.expand(JsonLdApi.java:819)
	at com.github.jsonldjava.core.JsonLdApi.expand(JsonLdApi.java:997)
	at com.github.jsonldjava.core.JsonLdProcessor.expand(JsonLdProcessor.java:146)
	at com.github.jsonldjava.core.JsonLdProcessor.toRDF(JsonLdProcessor.java:485)
	at org.eclipse.rdf4j.rio.jsonld.JSONLDParser.parse(JSONLDParser.java:68)
	at org.apache.any23.extractor.rdf.BaseRDFExtractor.run(BaseRDFExtractor.java:105)
	at org.apache.any23.extractor.html.EmbeddedJSONLDExtractor.extractJSONLDScript(EmbeddedJSONLDExtractor.java:147)
	at org.apache.any23.extractor.html.EmbeddedJSONLDExtractor.run(EmbeddedJSONLDExtractor.java:82)
	at org.apache.any23.extractor.html.EmbeddedJSONLDExtractor.run(EmbeddedJSONLDExtractor.java:53)
	at org.apache.any23.extractor.SingleDocumentExtraction.runExtractor(SingleDocumentExtraction.java:476)
	at org.apache.any23.extractor.SingleDocumentExtraction.run(SingleDocumentExtraction.java:256)
	at org.apache.any23.Any23.extract(Any23.java:300)
	at org.apache.any23.Any23.extract(Any23.java:452)
	at org.apache.any23.servlet.WebResponder.runExtraction(WebResponder.java:117)
	at org.apache.any23.servlet.Servlet.doGet(Servlet.java:82)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:635)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:475)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:624)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.ajp.AjpProcessor.service(AjpProcessor.java:403)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:796)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1366)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.URISyntaxException: Illegal character in path at index 6: Action &amp; Adventure
	at java.net.URI$Parser.fail(URI.java:2848)
	at java.net.URI$Parser.checkChars(URI.java:3021)
	at java.net.URI$Parser.parseHierarchical(URI.java:3105)
	at java.net.URI$Parser.parse(URI.java:3063)
	at java.net.URI.<init>(URI.java:588)
	at java.net.URI.create(URI.java:850)
	... 45 more
]]>
</error>
<issueReport>
```
Whether or not ampersands are permitted within jsonld or URI's is irrelivant. jsonld-java would be a better toolkit if it supported the escaping of ampersands should they be encountered.

**Comment by lewismc** [comment]
The variable (pathToResolve) which leads to the above can be located at https://github.com/jsonld-java/jsonld-java/blob/master/core/src/main/java/com/github/jsonldjava/utils/JsonLdUrl.java#L274 e.g. 
```
uri = uri.resolve(pathToResolve);
```
Is it too costly to merely use an URLEncoder as follows?
```
uri = uri.resolve(java.net.URLEncoder.encode(pathToResolve, "utf8"))
```

**Comment by lewismc** [comment]
I also note the presence of commentary in the containing method
```
        // TODO: some input will need to be normalized to perform the expected
        // result with java
// TODO: we can do this without using java URI!
```
Is use of the URLEncoder the proper solution here or was there some other intention?

**Comment by afs** [comment]
> `Illegal character in path at index 6: Action &amp; Adventure`

Index 6 is a space which is illegal In URIs.

**Comment by lewismc** [comment]
wow @afs thanks for chiming in here... this was lost on me and I had to do some digging to understand the context again :)

Looking into the schema.org markup I can see the following
```
{
    "@context": "http:\/\/schema.org",
    "@type": "Movie",
    "name": "The Lord of the Rings: The Fellowship of the Ring",
    "contentRating": "PG-13",
    "dateModified": "2020-03-16T08:36:57-07:00",
    "dateCreated": "2005-11-20T14:49:31-08:00",
    "url": "https:\/\/www.rottentomatoes.com\/m\/the_lord_of_the_rings_the_fellowship_of_the_ring",
    "datePublished": null,
    "productionCompany": {
        "@type": "Organization",
        "name": "New Line Cinema"
    },
...
    "genre": [
        "Action & Adventure",
        "Classics",
        "Drama",
        "Science Fiction & Fantasy"
    ]
}
```
In the **genre** array we can see the values... it occurs to be that this value should be allowed. Am I wrong?
Thanks @afs

**Comment by afs** [comment]
See https://schema.org/genre 
The value is text or URL.
The example for jSON-LD has 

    "genre": "http://vocab.getty.edu/aat/300021143"

In the example about, those are reasonable for text, but not for URLs.
So if the context is mapping "genre" to URIs, then that data does not conform.

I ran the JSON-LD at https://www.rottentomatoes.com/m/the_lord_of_the_rings_the_fellowship_of_the_ring
through jsonld-java v0.12.5, and it produced RDF triples including (Turtle format):

   []  schema:genre     "Drama" , "Classics" , "Action & Adventure" , "Science Fiction & Fantasy" ;

so they are coming out as strings.

**Comment by lewismc** [comment]
OK great. This issue can be resolved. We upgraded to 0.12.5 in Any23 so we can close this off. Thank you @afs I appreciate revisiting thus one :)
