### ISSUE TITLE
Nested properties, and more generally JSON_LD_1_1

### ISSUE THREAD

**Issue by jmvanel** [jsonld-java/jsonld-java#219]
I tested
Example 76: Nested properties
from the 1.1. spec (in progress):
https://json-ld.org/spec/latest/json-ld/#nested-properties

with the basic Java-json-ld program:
https://github.com/jsonld-java/jsonld-java#code-example

Adding this line in code:
```java
  options.setProcessingMode(JsonLdOptions.JSON_LD_1_1);
// or tried also
  options.setProcessingMode(JsonLdOptions.JSON_LD_1_1_FRAME);
```

and ... it fails ! :(
```
Exception in thread "main" com.github.jsonldjava.core.JsonLdError: invalid term definition: 1.1
	at com.github.jsonldjava.core.Context.createTermDefinition(Context.java:330)
	at com.github.jsonldjava.core.Context.parse(Context.java:279)
	at com.github.jsonldjava.core.Context.parse(Context.java:142)
	at com.github.jsonldjava.core.Context.parse(Context.java:286)
	at com.github.jsonldjava.core.JsonLdApi.expand(JsonLdApi.java:543)
	at com.github.jsonldjava.core.JsonLdApi.expand(JsonLdApi.java:997)
	at com.github.jsonldjava.core.JsonLdProcessor.expand(JsonLdProcessor.java:146)
	at com.github.jsonldjava.core.JsonLdProcessor.compact(JsonLdProcessor.java:51)
```

I found nothing regarding the status of Java-json-ld regarding JSON-LD 1.1 ;
I'm aware that this is a spec. in progress .

**Comment by ansell** [comment]
Any contributions to support JSON-LD 1.1 features would be appreciated. So far the new features from the developing spec (that I am aware of) have not been specifically linked to JSON-LD 1.1.

**Comment by gkellogg** [comment]
Not sure why you think that features being developed aren't linked to JSON-LD 1.1, as they're described in the [1.1 spec](https://json-ld.org/spec/latest/json-ld-api/) being developed by the CG, which is being used as input to the proposed WG (see [charter](https://json-ld.github.io/charter).

Main things of interest to people are:

* Scoped Contexts
* id maps and type maps (also for graphs)
* transparent nesting of properties.

In general, make JSON-LD look more like regular JSON used in the field and address issues that have been raised in the last several years.

**Comment by umbreak** [comment]
[@reverse special key on framing](https://json-ld.org/spec/latest/json-ld-framing/#reverse-framing) would be another interesting feature to implement.

**Comment by jeyendranbalakrishnan** [comment]
Hello, wondering if there are any plans to support the json-ld 1.1 spec in jsonld-java.
Thanks a lot!

**Comment by ansell** [comment]
Any features that are sent as Pull Requests will be looked at, but there is no active work being done by me or Tristan on jsonld-java to add features for 1.1.

**Comment by jeyendranbalakrishnan** [comment]
Thanks for the clarification, Peter!

**Comment by lroffia** [comment]
Access to the following "@context": "https://www.w3.org/ns/td.jsonld" raises the following:

com.github.jsonldjava.core.JsonLdError: invalid term definition: 1.1
	at com.github.jsonldjava.core.Context.createTermDefinition(Context.java:334)
	at com.github.jsonldjava.core.Context.parse(Context.java:281)
	at com.github.jsonldjava.core.Context.parse(Context.java:209)
	at com.github.jsonldjava.core.Context.parse(Context.java:144)
	at com.github.jsonldjava.core.Context.parse(Context.java:288)
	at com.github.jsonldjava.core.JsonLdApi.expand(JsonLdApi.java:550)
	at com.github.jsonldjava.core.JsonLdApi.expand(JsonLdApi.java:1027)
	at com.github.jsonldjava.core.JsonLdProcessor.expand(JsonLdProcessor.java:146)
	at com.github.jsonldjava.core.JsonLdProcessor.toRDF(JsonLdProcessor.java:505)
	at com.github.jsonldjava.core.JsonLdProcessor.toRDF(JsonLdProcessor.java:555)

With reference to the specification 1.1 should be considered as number (looking at the code it seems like it would be accepted only as string)
