### ISSUE TITLE
JsonLdError: loading remote context fails

### ISSUE THREAD

**Issue by HansBrende** [jsonld-java/jsonld-java#221]
I'm getting this error when I try to parse a simple json-ld object:

<pre>
com.github.jsonldjava.core.JsonLdError: loading remote context failed: http://json-ld.org/contexts/person.jsonld
	at com.github.jsonldjava.core.DocumentLoader.loadDocument(DocumentLoader.java:51)
	at com.github.jsonldjava.core.Context.parse(Context.java:195)
	at com.github.jsonldjava.core.Context.parse(Context.java:142)
	at com.github.jsonldjava.core.Context.parse(Context.java:286)
	at com.github.jsonldjava.core.JsonLdApi.expand(JsonLdApi.java:550)
	at com.github.jsonldjava.core.JsonLdApi.expand(JsonLdApi.java:1030)
	at com.github.jsonldjava.core.JsonLdProcessor.expand(JsonLdProcessor.java:152)
	at com.github.jsonldjava.core.JsonLdProcessor.toRDF(JsonLdProcessor.java:524)
	at org.eclipse.rdf4j.rio.jsonld.JSONLDParser.parse(JSONLDParser.java:71)
	... 37 more
Caused by: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1949)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:302)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:296)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1497)
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:212)
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:979)
	at sun.security.ssl.Handshaker.process_record(Handshaker.java:914)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1062)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:396)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:355)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:359)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:381)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237)
	at org.apache.http.impl.client.cache.CachingExec.callBackend(CachingExec.java:593)
	at org.apache.http.impl.client.cache.CachingExec.handleCacheMiss(CachingExec.java:357)
	at org.apache.http.impl.client.cache.CachingExec.execute(CachingExec.java:276)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:111)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
	at com.github.jsonldjava.utils.JsonUtils.fromURL(JsonUtils.java:301)
	at com.github.jsonldjava.core.DocumentLoader.loadDocument(DocumentLoader.java:49)
	... 45 more
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:387)
	at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:292)
	at sun.security.validator.Validator.validate(Validator.java:260)
	at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:324)
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:229)
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:124)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1479)
	... 69 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:145)
	at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:131)
	at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280)
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:382)
	... 75 more
</pre>

**Comment by ansell** [comment]
The likely culprits are you have an old JDK build or an old JSONLD-Java
dependency through Rio, similar to
https://issues.apache.org/jira/browse/ANY23-303 . Upgrade to the latest
JDK-8 build (161 or 162) and manually bump the JSONLD-Java dependency
version to see if that fixes it.

**Comment by HansBrende** [comment]
I updated my JDK version from 1.8.0_51 to 1.8.0_162 and it worked perfectly, thanks!
