### ISSUE TITLE
JsonLdError: loading remote context fails

### ISSUE THREAD

**Issue by nicolapaganotti1** [jsonld-java/jsonld-java#328]
I'm getting this error when I try to parse a simple json-ld object:
at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
 at [Source: (BufferedReader); line: 1, column: 2]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1851)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:707)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:632)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:1941)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:776)
	at com.github.jsonldjava.utils.JsonUtils.fromJsonParser(JsonUtils.java:202)
	at com.github.jsonldjava.utils.JsonUtils.fromReader(JsonUtils.java:184)
	at com.github.jsonldjava.utils.JsonUtils.fromInputStream(JsonUtils.java:165)
	at com.github.jsonldjava.utils.JsonUtils.fromInputStream(JsonUtils.java:118)
	at com.github.jsonldjava.utils.JsonUtils.fromJsonLdViaHttpUri(JsonUtils.java:380)
	at com.github.jsonldjava.utils.JsonUtils.fromURL(JsonUtils.java:355)
	at com.github.jsonldjava.core.DocumentLoader.loadDocument(DocumentLoader.java:72)
	... 56 more
com.github.jsonldjava.core.JsonLdError: loading remote context failed: http://www.w3.org/2009/08/skos-reference/skos.html
	at com.github.jsonldjava.core.DocumentLoader.loadDocument(DocumentLoader.java:74)
	at com.github.jsonldjava.core.Context.parse(Context.java:205)
	at com.github.jsonldjava.core.Context.parse(Context.java:150)
	at com.github.jsonldjava.core.Context.parse(Context.java:305)
	at com.github.jsonldjava.core.JsonLdApi.expand(JsonLdApi.java:550)
	at com.github.jsonldjava.core.JsonLdApi.expand(JsonLdApi.java:524)
	at com.github.jsonldjava.core.JsonLdApi.expand(JsonLdApi.java:849)
	at com.github.jsonldjava.core.JsonLdApi.expand(JsonLdApi.java:1027)
	at com.github.jsonldjava.core.JsonLdProcessor.expand(JsonLdProcessor.java:139)
	at com.github.jsonldjava.core.JsonLdProcessor.compact(JsonLdProcessor.java:49)
	
Caused by: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
 at [Source: (BufferedReader); line: 1, column: 2]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1851)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:707)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:632)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:1941)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:776)
	at com.github.jsonldjava.utils.JsonUtils.fromJsonParser(JsonUtils.java:202)
	at com.github.jsonldjava.utils.JsonUtils.fromReader(JsonUtils.java:184)
	at com.github.jsonldjava.utils.JsonUtils.fromInputStream(JsonUtils.java:165)
	at com.github.jsonldjava.utils.JsonUtils.fromInputStream(JsonUtils.java:118)
	at com.github.jsonldjava.utils.JsonUtils.fromJsonLdViaHttpUri(JsonUtils.java:380)
	at com.github.jsonldjava.utils.JsonUtils.fromURL(JsonUtils.java:355)
	at com.github.jsonldjava.core.DocumentLoader.loadDocument(DocumentLoader.java:72)
	... 56 more

**Comment by nicolapaganotti1** [comment]
{
  "@context": "https://schema.org",
  "@id": "https://www.fondazioneeinaudi.it/library?id=cb604b1f-3aff-46df-a743-acfb0a304aee",
  "@type": "Book",
  "name": "Teoria della struttura economica capitalistica : il metodo di Marx e i fondamenti della critica all'economia politica",
  "author": [{
    "@type": "Person",
    "@id": "http://viaf.org/viaf/87757503",
    "name": "Alessandro Vercelli"},{
    "@type": "Person",
    "@id": "http://viaf.org/viaf/80000001",
    "name": "Alessandro Vercelli 2"}],
  "publisher":  {
    "@type": "Organization",
    "@id": "http://viaf.org/viaf/132070792",
    "name": "Fondazione Luigi Einaudi onlus",
    "location": "Torino"},
  "datePublished":"1973",
  "bookFormat": "EPUB",
  "inLanguage": "it",
  "isPartOf": "Studi",
  "about": [{
    "@context": "http://www.w3.org/2009/08/skos-reference/skos.html",
    "@id": "https://thes.bncf.firenze.sbn.it/termine.php?id=810",
    "name": ["Economia", "Politica"]},
    {"@context": "http://www.w3.org/2009/08/skos-reference/skos.html",
    "@id": "https://thes.bncf.firenze.sbn.it/termine.php?id=596",
    "name": "Capitalismo"},
    {"@context": "http://www.w3.org/2009/08/skos-reference/skos.html",
    "@id": "https://thes.bncf.firenze.sbn.it/termine.php?id=585",
    "name": "Saggi"}]
}

It seems I cannot use http://www.w3.org/2009/08/skos-reference/skos.html as @context. Why?

**Comment by acka47** [comment]
> It seems I cannot use http://www.w3.org/2009/08/skos-reference/skos.html as @context. Why?

Because a JSON-LD context has to be a JSON document "used to map terms to IRIs", see the JSON-LD Spec at https://www.w3.org/TR/json-ld/#the-context.

I also don't see why you would use SKOS in the example as you do not seem to use any SKOS properties (like `prefLabel`) but just schema.org. If you remove the three occurences of `"@context": "http://www.w3.org/2009/08/skos-reference/skos.html"`, everything looks good, see the example in the JSON-LD playground at https://tinyurl.com/y37qauj7.

Please close the issue if you think it is resolved.
